
export default {
  IPPATSU: "Ippatsu",
  TANYAO: "Tanyao",
  PINFU: "Pinfu",
  RIICHI: "Riichi",
  DOUBLERIICHI: "Double Riichi",
  IIPEIKOU: "Iipeikou",
  FANPAI: "Fanpai",
  TSUMO: "Tsumo",
  SANSHOKUDOUJUN: "Sanshoku Doujun",
  ITSU: "Itsu",
  CHANTA: "Chanta",
  RINSHANKAIHOU: "Rinshan kaihou",
  CHANKAN: "Chankan",
  HAITEI: "Haitei",
  HOUTEI: "Houtei",
  CHIITOITSU: "Chiitoitsu",
  SANSHOKUDOKOU: "Sanshoku Dokou",
  SANANKOU: "Sanankou",
  SANKANTSU: "Sankantsu",
  TOITOI: "Toitoi",
  HONITSU: "Honitsu",
  SHOUSANGEN: "Shousangen",
  HONROUTOU: "Honroutou",
  JUNCHAN: "Junchan",
  RYANPEIKOU: "Ryanpeikou",
  CHINITSU: "Chinitsu",
  RENHO: "Renho",

  KOKUSHIMUSOU: "Kokushi Musou",
  CHUURENPOOTO: "Chuurenpouto",
  TENHO: "Tenho",
  CHIHO: "Chiho",
  SUUANKOU: "Suuankou",
  SUUKANTSU: "Suukantsu",
  RYUUIISOU: "Ryuuiisou",
  CHINROUTO: "Chinrouto",
  TSUUIISOU: "Tsuuiisou",
  DAISANGEN: "Daisangen",
  SHOUSUUSHII: "Shousuushii",
  DAISUUSHII: "Daisuushii"
}
